########################################################################
## Copyright(c) libgreen contributors.  See LICENSE file for details. ##
########################################################################

sudo: false

os:
  - linux
  - osx

language: c

compiler:
  - clang
  - gcc

# Container for C on linux does not include Python by default.
addons:
  apt:
    packages:
      - python2.7
      - valgrind

before_script:
  - pip install --user cpp-coveralls==0.3.10
  - pip install --user Sphinx==1.3.3
  # On OSX, user site directory is not on PATH.
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export PATH=$PATH:~/Library/Python/2.7/bin/;
    fi
  - mkdir build
  - cd build

script:
  # Build without tests.
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DGREEN_TESTS=OFF
  - make
  - make clean
  # Build again with tests and run them (fails if any leaks are found).
  #
  # On OSX, `brew install valgrind` is broken and `port install valgrind-devel`
  # is not possible because MacPorts is not provided on Travis-CI VMs.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cmake .. -DGREEN_TESTS=ON -DGREEN_GCOV=ON -DGREEN_VALGRIND=ON;
      make;
      CTEST_OUTPUT_ON_FAILURE=TRUE ctest -T memcheck;
    else
      cmake .. -DGREEN_TESTS=ON -DGREEN_GCOV=ON;
      make;
      CTEST_OUTPUT_ON_FAILURE=TRUE ctest;
    fi
  # Build docs.
  - sphinx-build -b html ../docs/ docs/
  # Send code coverage to coveralls.io.
  - coveralls -r .. -b . -e build/env/ -E '.*CMakeCXXCompilerId\.cpp' -E '.*CMakeCCompilerId\.c' -E '.*feature_tests.c' -E '.*feature_tests.cxx'
