########################################################################
## Copyright(c) libgreen contributors.  See LICENSE file for details. ##
########################################################################

sudo: false

os:
  - linux
  - osx

language: c

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build

script:
  - cmake .. -DGREEN_TESTS=OFF
  - make
  - cmake .. -DGREEN_TESTS=ON
  - make
  - make test
